apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: tas-scheduler
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: topology-aware-scheduler
      plugins:
        filter:
          enabled:
            - name: NodeResourceTopologyMatch
        score:
          enabled:
            - name: NodeResourceTopologyMatch
      # optional plugin configs
      pluginConfig:
      - name: NodeResourceTopologyMatch
        args:
          kubeconfigpath: "" # needs to be empty string
