apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nfd-master-topologyupdater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nfd-master-topology-updater
subjects:
  - kind: ServiceAccount
    name: nfd-master-topologyupdater
    namespace: node-feature-discovery
